### ISSUE TITLE
Feature Request: Emby Server support

### ISSUE THREAD

**Issue by Jdiesel87** [Hellowlol/HTPC-Manager#348] opened 2015-09-24 16:52 UTC
The ability to poll Emby Server for recently added/played files much like what is available for Kodi/Plex.

https://github.com/MediaBrowser/Emby.ApiClient.Javascript/blob/master/README.md

**Comment by Hellowlol** [comment] 2015-09-24 17:32
Duplicate of https://github.com/Hellowlol/HTPC-Manager/issues/181

**Closed as completed by Hellowlol** 2015-09-24 17:32 UTC
