### ISSUE TITLE
Request - option to toggle off active navbar item

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#302] opened 2015-08-06 07:19 UTC
Could a switch option be added into the theme settings to disable the active navbar items please?  It only works on a few items for me and I'm not a fan of how it looks on most of the themes.

**Comment by Hellowlol** [comment] 2015-08-06 07:24
Can do.

**Comment by bakman2** [comment] 2015-08-06 07:25
is this caused by my action ?

**Comment by Hellowlol** [comment] 2015-08-06 07:28
Haha, yeah. No biggie, we can make both happy :P

**Comment by thatbritguy** [comment] 2015-08-06 07:31
@Hellowlol Awesome, thanks.

@bakman2 I'm not sure but the only item that actually highlight when active for me is Plex.  The other items I have it doesn't work on are Sys Info, vnStat, Samsung Remote, Sonarr, Newznab, Torrents or CouchPotato.

**Comment by Hellowlol** [comment] 2015-08-06 07:33
I havnt tested this myself, i just checked for syntax errors. I think it would be very nice if it used the same color as when you "hover" over them.

**Comment by bakman2** [comment] 2015-08-06 07:37
I see it :( didn't fail for me as the menu items matched the id's. But I see that my "stats" has the ID of vnstat. Have to figure out a different way.

~~@Hellowlol I see an array of the menu items being generated is that coming from python somewhere ?~~ found it, not an option to modify this with the current active?

**Comment by Hellowlol** [comment] 2015-08-06 07:55
Its coming from the db as the menus can be reordered.

Edit: I dont know, im not that good with js/jquery so ill have to check (the reorder dash and navbar was a pr) But im sure we can fix this :)

**Comment by bakman2** [comment] 2015-08-06 08:19
Is it possible to determine the requested page ?

then it should be possible to build the array with an additional class in this part ?

```
 %if s.get(m.get('id')+'_enable'):
            menus['nav-${m.get('id')}'] = '<li class="nav-menu-item" id="nav-${m.get('id')|h, entity}"><a href="${htpc.WEBDIR}${m.get('id')|h, entity}/">${m.get('name') if s.get(m.get('id')+'_name').strip() == "" else s.get(m.get('id')+'_name')|h, entity}</a></li>';

        %endif
```

**Comment by Hellowlol** [comment] 2015-08-06 08:28
I dont think so, i think we have to solve this with js.

**Comment by fma965** [comment] 2015-08-06 09:18
i got an idea on the navbar thingy

**Comment by bakman2** [comment] 2015-08-06 09:20
@Hellowlol in default.js i see 

```
    path = window.location.pathname.split('/')
    $('#nav-'+path[1]).addClass('active')
```

~~this doesn't appear to work, not sure why, maybe move to the bottom ?~~
this works when moved to the bottom (after the menus have been created)

**Comment by Hellowlol** [comment] 2015-08-06 09:25
Hmm, i cant remember what that was used for, i tought it was for the tabs or something :P You can try :D

**Comment by fma965** [comment] 2015-08-06 09:28
haha it's funny you posted that code as that was my plan, i was gonna get the last part of the url and then use that as the class just like this code does. that said i don't think this would work for me, as i have remote.cyanlabs.net/htpc/NAME so it wouldn't be the second /

**Comment by fma965** [comment] 2015-08-06 09:29
path = window.location.href.substring(window.location.href.lastIndexOf( '/' ));
$('#nav-'+path).addClass('active')

would work on all cases.

**Comment by fma965** [comment] 2015-08-06 09:31
or 

path = window.location.href.split("/").pop();
$('#nav-'+path).addClass('active')

**Comment by bakman2** [comment] 2015-08-06 09:39
strip of the last /

```
 path = window.location.href.split("/").slice(0, - 1).pop()
   $('#nav-'+path).addClass('active')
```

**Comment by fma965** [comment] 2015-08-06 09:40
yep noticed that :D

**Comment by fma965** [comment] 2015-08-06 09:49
making PR to fix nav active

**Comment by Hellowlol** [comment] 2015-08-10 12:04
@raysguy Is this still needed? I havnt seen any themes that are affect by this (only checked some.)

**Comment by thatbritguy** [comment] 2015-08-10 18:40
The ones it doesn't look good on are moonlight, plexibility and sublime as the text color when highlighted doesn't match the text color when hovering.

**Comment by Hellowlol** [comment] 2015-08-10 18:50
Hmm, any reason why we cant change that?

**Comment by thatbritguy** [comment] 2015-08-10 19:21
Lol I have no idea :P I'll have a look if the feature is updated to see how it looks on those.

**Comment by Hellowlol** [comment] 2015-08-10 19:40
Well make it look like hover? I think that looks nice.

**Comment by Hellowlol** [comment] 2015-08-10 19:43
Hmm, i cant remember how that looks on tabs / pills

**Comment by Hellowlol** [comment] 2015-08-12 11:07
@raysguy I have finally found a solution that im happy with regarding the cache. I have never used so much time on such a small change. It was to slow, or fast enough and ate all my memory. I did a small test on 18500 images and it took 160ish sec and only used 90MB memory.. Ill start on this request after its merged.

**Comment by thatbritguy** [comment] 2015-08-12 11:29
Awesome that sounds great! :)

**Comment by Hellowlol** [comment] 2015-11-09 12:18
https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/default.js#L296
Sorry about this, i have been dragging my feet way to long regarding this request. Ill get it done asap.

**Comment by Hellowlol** [comment] 2015-11-09 22:16
There is now a option in the general settings page where you can turn it off.

**Closed as completed** 2016-02-04 11:33 UTC
Labels: Feature request, TODO
