### ISSUE TITLE
Bug: newznab search

### ISSUE THREAD

**Issue by duramato** [Hellowlol/HTPC-Manager#359] opened 2015-10-09 16:50 UTC
If i add 6box.me as an indexer ,and try a search it wont show the indexer name..
SS of what im talking about:
![image](https://cloud.githubusercontent.com/assets/10121067/10400002/29aaa9ec-6eae-11e5-8b51-64856a0a13ea.png)

**Comment by Hellowlol** [comment] 2015-10-09 17:15
Thanks, it's not a bug per se. It's more of a consequence off the indexers having a hard time keeping to a simple standard. :p n this case there is no title and the description field is a empty string. Only way I can fix this if I have the raw response api response . Do you know if registration is open and that the api is accessible from a free account?

**Comment by duramato** [comment] 2015-10-09 17:17
Yes they have open registrations ,and its 100% free

**Comment by Hellowlol** [comment] 2015-10-09 17:19
Ok. I'll try to fix it tomorrow.

**Comment by Hellowlol** [comment] 2015-10-12 22:01
This should be fixed in the latest update.

**Closed as completed by Hellowlol** 2015-10-12 22:01 UTC
Labels: Fixed

**Comment by duramato** [comment] 2015-10-12 22:24
@Hellowlol ive updatedbut now it seems it is not showing any results
and i gethis in the log:

```


2015-10-12 23:23:18 webui.console.errors    ERROR   {'message': u"Uncaught TypeError: Cannot read property 'length' of undefined", 'line': u'9', 'file': u'http://***********.biz.tm:8085/js/libs/jquery.min.js', 'page': u'http://***********.biz.tm:8085/newznab/'}
2015-10-12 23:23:16 modules.newznab DEBUG   Fetching search results from http://6box.me/api?o=json&apikey=********************************&t=search&q=Gotham&extended=1
2015-10-12 23:23:16 modules.newznab DEBUG   Fetching search results from http://www.usenet-crawler.com/api?o=json&apikey=********************************&t=search&q=Gotham&extended=1
2015-10-12 23:23:16 modules.newznab DEBUG   Searching for Gotham category on indexer all
```

**Comment by Hellowlol** [comment] 2015-10-12 22:28
Try restarting htpc manager again

**Comment by duramato** [comment] 2015-10-12 22:30
@Hellowlol ah ,thanks it workedit now shows results :D ,and can say your fix also worked!! :smile:

**Comment by Hellowlol** [comment] 2015-10-12 22:39
Any change your not using git but the source updater?

**Comment by duramato** [comment] 2015-10-12 22:42
@Hellowlol Im using the built in updater
