### ISSUE TITLE
Newznab issue if provider ignores o=json

### ISSUE THREAD

**Issue by l-t-k** [Hellowlol/HTPC-Manager#244] opened 2015-07-09 16:26 UTC
First, a lot of hard seem to been done since I was here for the last time. Great work! :D. I'm trying to add my local spotweb installation as a newznab search provider, but it fails. No results show up and the log can be found at the end of this post. I use spotweb as a newznab provider successfully with couch, sick and headphones. I think it needs http:// to connect, but when I enter this information, the http:// is cut off after save.

`2015-07-09 18:19:36 :: cherrypy.error.3057225836 :: ERROR :: [09/Jul/2015:18:19:36] HTTP Traceback (most recent call last):
  File "/opt/htpcmanager/libs/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/opt/htpcmanager/libs/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/htpcmanager/libs/cherrypy/lib/jsontools.py", line 64, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/htpcmanager/libs/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/htpcmanager/modules/newznab.py", line 291, in search
    f.append(res.json()['channel'])
TypeError: list indices must be integers, not str`

**Comment by Hellowlol** [comment] 2015-07-09 16:33
Does spot web have identical api as newznab? Can you take a screenshot of the about page, newznab settings page (mask your apikey) and provide a full log with loglevel debug?

Edit: thanks!

**Comment by l-t-k** [comment] 2015-07-09 21:50
Not sure, if it's identical. Dropped that question on the spotweb github page. I think yes, because under couch, HP and sickrage/sickbeard I just add a custom newznab server to use spotweb. 
Screen:
![1](https://cloud.githubusercontent.com/assets/3150962/8607641/be35d8f0-2694-11e5-97bb-ba7c87e51148.jpg)

I think this is the issue: (can't find any more related logs on debug level):
`Unable to fetch information from: http://localhost/spotweb/api?o=json&apikey=LOLREMOVED&t=caps No JSON object could be decoded`

**Comment by Hellowlol** [comment] 2015-07-09 21:59
Okei, so it fails when it tries to get indexer categories. You should change your apikey btw, you forgot to remove it from the log :P

**Comment by Hellowlol** [comment] 2015-07-09 22:01
if you go to http://localhost/spotweb/api?o=json&apikey=LOLREMOVED&t=caps manually do you get a response at all? and if you do can you post it?

**Comment by l-t-k** [comment] 2015-07-09 22:27
Lol, how stupid... 

Spotweb is using same api:
https://github.com/spotweb/spotweb/issues/80#issuecomment-120162611

Response:
![1](https://cloud.githubusercontent.com/assets/3150962/8608344/5fbeb3f4-269a-11e5-9f0c-fa8963afb5ee.jpg)

**Comment by Hellowlol** [comment] 2015-07-09 22:30
Well they might have but that response isnt json...

**Comment by Hellowlol** [comment] 2015-07-09 22:39
@kooimens can you update and try again?

**Comment by madclicker** [comment] 2015-07-09 22:52
Same as the free newznab and nezbd servers.

**Comment by Hellowlol** [comment] 2015-07-09 22:55
They dont support json? well isnt really a problems, it 's just annoying. You cant say that the api is the same if you dont support the output :P

**Comment by l-t-k** [comment] 2015-07-09 23:00
Nothing changed. I use log-level debug, but I see a small amount of information in my logs. The error:
`cherrypy.error.3050752876  ERROR   [10/Jul/2015:00:56:25] HTTP Traceback (most recent call last):`

**Comment by Hellowlol** [comment] 2015-07-09 23:06
Delete your log and try again and give me the full log please. It should at the very least give some other more info...

Also take the content of http://localhost/spotweb/api?o=json&apikey=LOLREMOVED&t=caps and dump it in a pastebin (remember to remove your key this time :P)

**Comment by l-t-k** [comment] 2015-07-09 23:23
Log output:
http://pastebin.com/zRKFqnFd

**Comment by l-t-k** [comment] 2015-07-09 23:27
XML output:
http://pastebin.com/4V4kCUXn

**Comment by thejrose1984** [comment] 2015-07-10 00:53
So does this mean HTPC's newznab module isn't compatible with nZEDb?

**Comment by Hellowlol** [comment] 2015-07-10 05:53
If nzedb don't support Json and /or has a different api yes.

**Comment by Sweepr** [comment] 2015-07-10 15:08
Read this: https://github.com/lad1337/XDM/issues/83

**Comment by madclicker** [comment] 2015-07-10 16:10
I don't know about spotweb, but nZEDb and the free version of newznab 
return the caps in XML only. The searches still support json. This is on 
of the things I fixed first. You can take it from PyTunes if you want.

**Comment by Hellowlol** [comment] 2015-07-10 16:20
@Sweepr thanks for the link.I have already found that one and it's easy to work around. But I do think it should be fixed in spotweb instead of every other app that uses the api.

**Comment by Hellowlol** [comment] 2015-07-10 16:22
@madclicker cheers

**Comment by Sweepr** [comment] 2015-07-10 17:38
http://spotweburl/api?t=search&q=Linux&apikey=APIKEY&o=json

Removed the t=caps, now i do get Json?

**Comment by Sweepr** [comment] 2015-07-10 18:02
Tested this API string on nZEDb aswell and above string without "'t=caps" outputs Json, but as soon as i add the t=caps i get XML again,

**Comment by Hellowlol** [comment] 2015-07-10 18:39
That just confirms what madclicker said :)

**Comment by Sweepr** [comment] 2015-07-10 18:47
Yes, i wanted to check this for myself, making 100% sure

**Comment by madclicker** [comment] 2015-07-10 21:28
I wouldn't lead you girls astray.

**Comment by Hellowlol** [comment] 2015-07-11 08:23
Haha, thanks. I just tried to fix this and ended up with dog disabling the api. I'll give it another go when the kids are in bed
I this need to check that there xml response and spotweb have the same markup and add some error handling

**Comment by Hellowlol** [comment] 2015-07-11 10:07
Should be fixed in the lastest commit

**Closed as completed** 2015-07-11 10:06 UTC
Labels: bug / issue, wontfix

**Comment by thejrose1984** [comment] 2015-07-11 13:10
Nope, at least not for nZEDb - still shows caps at the end

**Comment by Hellowlol** [comment] 2015-07-11 13:50
@thejrose1984 caps where? Log please.

**Comment by Hellowlol** [comment] 2015-07-11 13:51
@kooimens can you confirm that this works now?

**Comment by l-t-k** [comment] 2015-07-11 15:57
Although the categories do show up and are correct I can't find anything. Log:
http://pastebin.com/tPfsV7VP

This:
![1](https://cloud.githubusercontent.com/assets/3150962/8634374/a9b6d1c8-27f6-11e5-9a2b-68aff2457112.jpg)

**Comment by thejrose1984** [comment] 2015-07-11 16:00
As of now, the log is massive and cannot send to you. If I send you partial logs, you tell me you cannot help. So the only viable alternative is you tell me SPECIFICALLY what you're looking for in the log.
http://pastebin.com/55Ys1j6L

**Comment by Hellowlol** [comment] 2015-07-11 16:07
@thejrose1984 sure your settings is ok? That url looks fucked up.

**Comment by thejrose1984** [comment] 2015-07-11 16:08
If you're referring to the API key, I purposely put astericks since the log exposes the API key whereas other apps have their keys concealed in the logs...

**Comment by Hellowlol** [comment] 2015-07-11 16:08
@kooimens can you try to search the spotweb app manually? Do they return json or xml?

**Comment by thejrose1984** [comment] 2015-07-11 16:11
As for my settings...
![2015-07-11 12_10_30-htpc manager](https://cloud.githubusercontent.com/assets/7573083/8634422/e3d43fa2-27c5-11e5-9473-8271a8686273.png)

I removed the API key before making the screenshot...

**Comment by Hellowlol** [comment] 2015-07-11 16:14
Well there isn't a extension to the URL? Is that something you have removed? Also I don't think apio=json is a valid parameter

**Comment by thejrose1984** [comment] 2015-07-11 16:15
That isn't something I control though, that's HTPC as far as I can see...especially since I showed you what I have entered into the settings page

**Comment by Hellowlol** [comment] 2015-07-11 16:17
so what the URL to the server then? Nzb-app? Really?

**Comment by thejrose1984** [comment] 2015-07-11 16:18
http://nzedb-app

Which is clearly showed in my screenshot...

**Comment by Hellowlol** [comment] 2015-07-11 16:19
So this is self hosted? Tried writing the ip to computer?

**Comment by thejrose1984** [comment] 2015-07-11 16:22
Yes it is self-hosted and tried using the resolved IP address just now and it is the same result...and if you look at the screenshots for spotweb above you'll notice that is self hosted as well...the issue is with self hosted indexers from what I can see in this issue, the logs presented, and troubleshooting done. Using hosted indexers such as usenet-crawler and 6box do not have this issue

**Comment by Hellowlol** [comment] 2015-07-11 16:27
Wipe the log and search again. Post that log after you have removed the api key. The log lines you give me should be impossible there is missing a ?

**Comment by thejrose1984** [comment] 2015-07-11 16:28
I also tested without nZEDb and the other indexers (usenet-crawler, 6box, and oznzb) work fine.

**Comment by thejrose1984** [comment] 2015-07-11 16:31
http://pastebin.com/aG604F5i
![2015-07-11 12_34_36-](https://cloud.githubusercontent.com/assets/7573083/8634512/3bad4072-27c9-11e5-9c1a-41505114241c.png)

**Comment by l-t-k** [comment] 2015-07-11 16:48
@Hellowlol I have no idea how to check tbh. Maybe, @Sweepr can you confirm a manual search on the spotweb app is json or xml output?

**Comment by Hellowlol** [comment] 2015-07-11 17:08
@thejrose1984 they can't be all in the log. Cmon I forgotten my magic bowl at home please help me. Thank you for giving me a heads up regarding apikey in log. As they are in a different table in the dnb they aren't included.

**Comment by Hellowlol** [comment] 2015-07-11 17:14
@kooimens http://ip/api?o=json&apikey=123&t=search&q=Terminator&extended=1

**Comment by thejrose1984** [comment] 2015-07-11 17:23
@Hellowlol I can't help you if you don't tell me exactly what I'm supposed to look for. I'm not a developer, I'm a system administrator. I can provide logs, change software, provide system information, but if your application has errors and simply tell me "provide logs" that's like telling me "I want to be President of the Earth"

It's all well and good, but it does nothing to help me help you figure out the problem...

**Comment by thejrose1984** [comment] 2015-07-11 17:29
Also...looked again and seems all API keys are exposed in the logs from the newznab module...which makes sense because if nZEDb's API is exposed, why wouldn't the others...

This needs to be fixed

**Comment by l-t-k** [comment] 2015-07-11 17:42
json?
http://pastebin.com/gu4zmL9T

**Comment by Hellowlol** [comment] 2015-07-11 19:02
@thejrose1984 your not suppose to look for anything, i will look for it. I can't tell want to look for because I'm not sure myself. I do know your giving me snippets where it's logged as error which in this case don't don't help me at all. I need the entire thing with info, debug and the shit. Just use a search and replace function from a editor to remove your api keys.

Use the download log button from the log page, remove apikey, dump the shit i a pastebin and I'll take it from there. 

All apikeys regarding nzb is not censored in the logs as they are in a different table in the db . I'll fix that soon enough, thank you bringing that to my attention.

@kooimens thank you! That response isn't even close to the one returned from newznab :(

**Comment by Hellowlol** [comment] 2015-07-11 20:25
@kooimens Can do do it again so we get the xml response (search on the same thing as last time. ) http://ip/api?o=xml&apikey=123&t=search&q=Terminator&extended=1

**Comment by thejrose1984** [comment] 2015-07-12 11:51
API keys hidden in log, but results seemed to be the same even though I can clearly see the URL format has changed.
http://pastebin.com/Re3mgyQz

**Comment by Hellowlol** [comment] 2015-07-12 11:57
The URL hasn't changed I haven't touched them at all. Dunno what happen with the other log. Can you manually type in the same URL as htpc manager tries in the browser and check what response you get there? Copy the output to a pastebin. Also try switching back to ip of the computer (as the URL is correct now)

**Comment by thejrose1984** [comment] 2015-07-12 12:07
Using IP address - http://pastebin.com/kicAWpTW
Using hostname - http://pastebin.com/X0x9vzhU

Far as I can see there is NO difference whether I use the hostname or IP address...
In fact, I did a test to confirm that it does not matter if I use IP address or resolved hostname on ANY module within HTPC Manager...

**Comment by Hellowlol** [comment] 2015-07-12 12:23
Good, but the log revealed the reason. Nzedb returns the same shit as spotweb (but with extra info) I tried to add a work around that that but I didn't include nzedb

**Comment by Hellowlol** [comment] 2015-07-12 12:39
So in short spotweb and nzbed will be unsupported until the fix there api or if any want to changes mine to use xml. (Read never)

**Comment by Hellowlol** [comment] 2015-07-12 12:57
@madclicker is there a paid version of nzbed?

**Comment by thejrose1984** [comment] 2015-07-12 13:43
@Hellowlol from the screenshot I gave you it looks like nZEDb supports JSON and XML so I don't understand your previous comment...

**Comment by Hellowlol** [comment] 2015-07-12 14:22
Yes, they mostly do but there json response isn't the same even if the api is the same... Can you search on the same thing and with o=xml and dump that to a pastebin?

I'll check if there xml response is the same, it it is I'll set a half hour to work on it.

Read the api: it states the search results should be a list of items. I don't think this will work.

**Comment by l-t-k** [comment] 2015-07-13 22:12
@Hellowlol In case you still need the xml response:
http://pastebin.com/RJ8cVpWb

**Comment by Hellowlol** [comment] 2015-07-13 22:15
I did, thanks!
@thejrose1984 can i have the xml results from a search on nZEDb aswell?

**Comment by l-t-k** [comment] 2015-08-27 13:15
@Hellowlol, you see any chance to fix this?

**Comment by Hellowlol** [comment] 2015-08-27 13:57
Fix what? The issue is rather long :p

**Comment by thejrose1984** [comment] 2015-08-27 15:07
Wait, this is still a thing?

**Comment by Hellowlol** [comment] 2015-08-27 15:14
I didn't think so as its closed, but I'm not sure what @kooimens meant

**Comment by thejrose1984** [comment] 2015-08-27 15:16
@kooimens nothing to "fix" because it's a matter of query results. Have you had a chance to read the comments above?

**Comment by l-t-k** [comment] 2015-08-30 14:25
Ah I see. I understand the issue partially. You asked for the xml response as one of the last comments. So I was just curious if it helped you out to find a way to support these indexers in future.

**Comment by Hellowlol** [comment] 2015-08-30 14:36
Yeah, I wanted to see how it looked. It's not gonna work until they provide a newznab api as they "advertise"..

**Comment by madclicker** [comment] 2015-08-31 02:48
Easy.

**Comment by Hellowlol** [comment] 2015-08-31 06:05
^^

**Comment by Hellowlol** [comment] 2015-10-12 08:10
Im gonna change from o=json til xml so we can support additional indexers. Hopefully it will support spotweb and nzbed

**Comment by l-t-k** [comment] 2015-10-12 16:26
Very nice! Ping me if you need some help testing.

**Comment by Hellowlol** [comment] 2015-10-12 22:03
@kooimens Can you try to add your spotweb indexer? and if you have access to a nzbedb can you test that as well?
@thejrose1984 Can you try your nzedb to htpc-manager and see if it works now?

**Comment by l-t-k** [comment] 2015-10-13 17:47
Fetching categories goes fine:
![1](https://cloud.githubusercontent.com/assets/3150962/10463174/3741954c-71e3-11e5-8d9f-0d0bb830b27e.jpg)

Search isn't working. Debug log:
http://pastebin.com/zhdrNLZi

Edit: this is for spotweb

**Comment by Hellowlol** [comment] 2015-10-13 18:07
@kooimens
Can you call the http://ip:port/newznab/search?q=Game%20of%20thrones&cat=&indexer=spotweb

Copy the reponse. Post it here or it your prefer you can email it to me on hellowlol1@gmail.com

**Comment by l-t-k** [comment] 2015-10-13 18:31
http://pastebin.com/pLp6nSPn

**Comment by Hellowlol** [comment] 2015-10-18 12:56
@kooimens any chance you can get me access to a spotwebserver? Good news its that nzedb work now

**Comment by l-t-k** [comment] 2015-10-18 19:52
http://spotweb.be/ use this api:
f850c3f0d3c2160bfca7dcda4b6b6293

**Comment by Hellowlol** [comment] 2015-10-18 21:02
@kooimens Ok, it should work with the latest update. Let me know.

**Comment by l-t-k** [comment] 2015-10-19 11:08
Works excellent now! Great work and many thanks again.

**Comment by Hellowlol** [comment] 2015-10-19 11:10
remember to change the api key ^^

**Comment by l-t-k** [comment] 2015-10-19 11:15
Yeah, good one;)

**Comment by thejrose1984** [comment] 2015-11-24 14:30
@Hellowlol sorry for the late response; had to put this on the far, far, away back burner. anyway, finally got around to deploying a fresh instance of nZEDb over the weekend and integrates fine with HTPC.

**Comment by Hellowlol** [comment] 2015-11-25 22:18
Thanks for getting back to me.
