### ISSUE TITLE
Miscellaneous bugs with Plex module

### ISSUE THREAD

**Issue by raysguy** [Hellowlol/HTPC-Manager#105] opened 2015-03-27 17:39 UTC
As requested I'm adding the Plex bugs into a new issues.  Thanks for looking into these.  On the Dashboard the "Latest Movies" section loads correctly but the "Latest TV Shows" remains blank (no placeholder or anything), and within the Plex module of Manager the thumbnails for movies/shows are rather low resolution, whereas those in the CouchPotato area are crisp and sharp.

**Comment by Hellowlol** [comment] 2015-03-27 17:49
Can you paste your the response of ip:port/plex/GetRecentShow to pastebin
Paste your log to pastebin.
 Are there any console errors in your browser?
 What browser and version number?

**Comment by raysguy** [comment] 2015-03-27 17:52
Just wanted to update this here and let you know that with regards the dash module it hasn't worked for me at all since I first started using HTPC-Manager a few days ago.  I just updated my installation with your reversion from a few hours ago but it persists.  I'll grab that other info you asked for and post you the link.

**Comment by raysguy** [comment] 2015-03-27 18:43
Here is the response: http://pastebin.com/Z6Z6vchm

Here is the log: http://pastebin.com/vWAGC47F (errors shown occur every time HTPC-Manager loads but it doesn't seem to generate anything when I visit the link you mentioned.  Hope that helps.

**Comment by Hellowlol** [comment] 2015-03-27 18:50
@raysguy ah crap the command was ip:port/plex/GetRecentShows can you try again?

**Comment by raysguy** [comment] 2015-03-27 19:14
No problem.  Results are here: http://pastebin.com/mHyDBabK  Need to check console with Safari after a reboot.

Log which is now capturing the error which occurs loading that page:  http://pastebin.com/c3E0kXia

**Comment by Hellowlol** [comment] 2015-03-27 19:26
wipe the log. Enable debug logging and try again?

**Comment by raysguy** [comment] 2015-03-28 00:51
This is the new Safari console error message - same as before - http://pastebin.com/mbJ5yZSA

**Comment by Hellowlol** [comment] 2015-03-28 00:55
That's fine, that isn't related.

**Comment by raysguy** [comment] 2015-03-28 00:57
I already had debug logging enabled but I reset it as requested and re-tested the link.  These are errors that show up every time I try to load the page: http://pastebin.com/KPCxNNdJ

**Comment by Hellowlol** [comment] 2015-03-28 01:12
Ok I didn't notice that in your privious log.

I need your xml to figure this out. Go to http://pmsip:pmsport/library/sections

**Comment by raysguy** [comment] 2015-03-28 01:17
Here's the XML: http://pastebin.com/i8G1kurL

**Comment by Hellowlol** [comment] 2015-03-28 07:33
Thanks. I have to make a seperate branch for you to use so we can debug this properly.  I suspect it fails https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/plex.py#L168 so I need to have all the episodes. I'll give you a link to a new branch later.

**Comment by raysguy** [comment] 2015-03-28 07:40
Thanks, I'm happy to provide whatever info you need to try and debug it.

**Comment by Hellowlol** [comment] 2015-03-29 01:59
Use this branch: https://github.com/Hellowlol/HTPC-Manager/tree/plexsucks
go to: http://localhost:8085/htpc/plex/GetRecentShows
grab the content post it to paste bin.

**Comment by raysguy** [comment] 2015-03-29 03:03
Here's the content: http://pastebin.com/9Zqc585H
I see an empty container for Latest TV Shows on the dash now at least.

**Comment by Hellowlol** [comment] 2015-03-30 06:27
@raysguy Can you update the plexsucks branch and try again. 
Does the recent show appear? if not paste the content of go to: http://localhost:8085/htpc/plex/GetRecentShows
and full debug log.

**Comment by raysguy** [comment] 2015-03-30 06:36
Awesome, recent shows are now appearing on the dash with that latest update! Thanks.

**Comment by Hellowlol** [comment] 2015-03-30 06:52
Ok, ill add that to the master2 branch later. So now its only the question about tvshow dupes. Does that still appear?

**Comment by raysguy** [comment] 2015-03-30 07:12
Yeah, the dupes still appear in the TV shows section.  

Also just noticed another Plex bug - when I click on a movie or tv episode and the pop up appears, if I have Plex Home Theater open on my Mac there is a button which says "Play on Plex Home Theater".  However, when I click on it nothing at all happens other than the pop up closes.  Nothing shows up in the logs though.  I should mention that when an item is currently playing on Plex Home Theater it is shown at the top of the Plex page and the play/pause etc controls do work on to control what is playing in PHT.

**Comment by Hellowlol** [comment] 2015-03-30 07:30
Ok, can you start htpc manager with loglevel debug so we get some logs. I dont use pht but it looks like have to install it

**Comment by raysguy** [comment] 2015-03-30 08:18
Thanks.  Here are recent debug logs - http://pastebin.com/NzDJ79Eg

The "Playing  + item +  on player 192.168.1.11" is the entry that is triggered by me clicking the "Play on PHT" button

**Comment by Hellowlol** [comment] 2015-03-30 08:19
just pushed a a change, can you try again?

**Comment by Hellowlol** [comment] 2015-03-30 08:22
btw, the paste was private, i cant see it ;)

**Comment by raysguy** [comment] 2015-03-30 08:28
Oops sorry, meant to select unlisted not private.  Should be fixed now.

**Comment by raysguy** [comment] 2015-03-30 08:30
Updated with latest change but I can't run htpc now.  Here's what I see in terminal when I try: http://pastebin.com/gg28Q3wL

**Comment by raysguy** [comment] 2015-03-30 08:53
Manually fixed it - just a rogue ")" on line 955 of plex.py.  Thankfully terminal pointed me right to it!

Here are the recent logs after your latest change: http://pastebin.com/wUzCLJJv

**Comment by Hellowlol** [comment] 2015-03-30 09:12
Nice!,  sorry for the typo, im at work so i have no way of testing this before i push. Try again?

**Comment by raysguy** [comment] 2015-03-30 10:46
No worries - that's quite some commitment editing from work.  Good job!  Here are the latest logs: http://pastebin.com/69qEEvYx

**Comment by Hellowlol** [comment] 2015-03-31 12:47
Ok, I have found a solution for play. The problem is only the dupe episodes... I have no idea how to fix that

**Comment by Hellowlol** [comment] 2015-03-31 22:44
@raysguy can you update and test the play command again?

**Comment by raysguy** [comment] 2015-03-31 23:06
Hi, just updated and tested play and it works a treat thanks. Tested on both PHT and iPhone.

For the dupe issue is there any info in the XML at ip:port/library/sections/ that could be used to filter out certain sections?  Even if I have to manually add them into the plex.py file that'd be fine.

Also is there a way I can reorder how items appear in the plex section?  Plex sorts shows with "The" in the title under the second word of the title, whereas in HTPC all shows starting with "The" are sorting together under T.  Wondered if it was possible for me to adjust that at all.

**Comment by Hellowlol** [comment] 2015-03-31 23:17
Im not realt sure how to handle it, you have a strange setup. I can add a ignorere list but that will everything. 

So say you have a section called dads show and kids show if both point to the same folder neither I'll be scanned. 

I havnt forgotten your request I'll see if I can't fix that tomorrow

I don't think it is, how would like to have it?

**Comment by raysguy** [comment] 2015-03-31 23:31
Ah yeah, there's a fair bit of overlap so I'd end up with a lot of the main shows I| watch unscanned.  Thanks for looking into all this.

For sorting I'd like it if things were ordered the same as Plex, e.g. Firefly, The Flash, The Following, Forever, Fresh Off The Boat

At the moment in HTPC it's ordered Firefly, Forever, Fresh Off The Boat; then under the Ts I have The Casual Vacancy, The Flash, The Following, The Game etc

**Comment by Hellowlol** [comment] 2015-03-31 23:39
I just noticed there was some sorting option, even a dupe so hopefill ill get this sorted.

**Comment by raysguy** [comment] 2015-03-31 23:40
That's awesome news, thanks.

**Comment by Hellowlol** [comment] 2015-04-01 21:33
@raysguy can you update and see if if the last push resolves your issue?

**Comment by raysguy** [comment] 2015-04-02 10:39
Using a 13" Retina MacBook pro so 2560x1600.

Interestingly, since we last checked the CP images now seem to suffer from a lower quality too.  The only thing that has changed since the last time I checked is that I've installed PIL so I don't know if that's a factor.

**Comment by Hellowlol** [comment] 2015-04-02 10:58
i bet it is, if pil is installed it will resize images to the wanted resolution, if it's not installed it will just return the original image.  

This is done because speed as the image can be huge and the typical size of a resized image is less then 6 kb

**Comment by raysguy** [comment] 2015-04-02 11:23
I wish it could pull the artwork that Plex has already downloaded without losing quality and then cache the files.

**Comment by Hellowlol** [comment] 2015-04-02 12:17
I dont think they would be good a solution. Think 1k images each with a size of 600kb. I'll rather tune the resize so it look good but uses less bandwidth.

Since I don't have a good screen do you think find the sweet spot regarding image resolution?

**Comment by Hellowlol** [comment] 2015-04-02 20:41
Okei so i have found the bug its a silly one.. :P. And i can say not resizing the images are not a option! 

I disabled delete the entire cache and tried again. 

Just my movies in plex is 460 MB, keep in mind that ALL my images in ALL the modules are prox 250 MB. The page was insanely slow.

The good new is that the images will now be resize with pil so the image quality should be equal to kodi etc. 

I added a option so you can test this yourself :)

**Comment by Hellowlol** [comment] 2015-04-02 20:43
https://github.com/Hellowlol/HTPC-Manager/tree/pleximages

**Comment by raysguy** [comment] 2015-04-03 17:01
Thanks, I've been testing this out.  Have to say I quite like the resize disable option as the images look so sharp.  Once it's cached them I haven't noticed any slowdown in the page speed.  Tried re-enabling resize but it reverted to the previous fuzzy images unfortunately.  Which values would I need to change in the plex.py module to specify a resolution so I can experiment with finding the optimum values?

There are a couple of side-effects with this branch though.  When you click on a movie the pop up box no longer has the "frosted" overlay on the background image so the synopsis etc text is unreadable on most of them.  Also in the shows section if you click on a show to bring up the episode list, when you click on an episode the layout of the popup is messed up as the frameshot of the episode is no longer resized.

**Comment by Hellowlol** [comment] 2015-04-03 17:29
There certenly are side effects. The branch was intended so you could see the difference .If resize is disabled the img will not be frosty etc I'll see if I can fix that. I'll see if there is a option regarding o in plex api. The images that are to big can be fixed with css.

So play with the sizes you need to edit plex.js look a call like this https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/js/plex.js#L101

**Comment by raysguy** [comment] 2015-04-03 17:59
Ah okay. I'll have a play around with some values when I get home later. I'd seen the o option in the py file but wasn't sure what to do with it.

**Comment by Hellowlol** [comment] 2015-04-03 18:27
O = opacity :)

**Comment by raysguy** [comment] 2015-04-03 20:15
Cheers, still picking up the more technical stuff as I go along :)

Btw forgot to mention but I realised the movie tab in the Plex module is actually missing most of my movies. It had picked them up from three libraries but is actually skipping the main one which is actually named "Movies". I think this might have been the case before the latest changes though to be honest, but can't be sure.

**Comment by Hellowlol** [comment] 2015-04-03 21:46
what are the file path and name of all your sections?

**Comment by raysguy** [comment] 2015-04-03 22:28
They should be all in the xml I posted on pastebin

**Comment by Hellowlol** [comment] 2015-04-03 22:34
Yeah I edit my post but you can't see that when your respond from the email :)

**Comment by raysguy** [comment] 2015-04-03 23:23
Haha I was also responding via the emails either which is why I couldn’t find it.  Got it now though: http://pastebin.com/i8G1kurL <http://pastebin.com/i8G1kurL>

It’s section 6 titled just “Movies”.

**Comment by Hellowlol** [comment] 2015-04-06 11:53
What is the path for that section?

**Comment by raysguy** [comment] 2015-04-06 12:26
/library/sections/6/composite/1427450448

I think that is the path you wanted?

**Comment by Hellowlol** [comment] 2015-04-06 16:09
No the file/folder path

**Comment by raysguy** [comment] 2015-04-06 16:15
These are the folder paths that the library uses:
"/Volumes/Movies/Disney Movies"
"/Volumes/Movies/Ray Ray Movies"
"/Volumes/Movies/2D Movies"

**Comment by Hellowlol** [comment] 2015-04-06 19:40
Can you test the styxit version and see if your missing movies there aswell?

**Comment by Hellowlol** [comment] 2015-04-27 16:15
Can I close this now?

**Comment by raysguy** [comment] 2015-04-27 17:36
Yeah all movies are showing up in current version thanks.

Only bug I see now in Plex is in the TV section where "iZombie" comes at the end of the list after "Zen".  Think it is just a random side-effect from sorting changes for items starting with "The".

**Closed** 2015-04-28 05:15 UTC
Labels: bug / issue
