### ISSUE TITLE
Emby Support

### ISSUE THREAD

**Issue by trixery** [Hellowlol/HTPC-Manager#416] opened 2016-01-16 08:40 UTC
Hello! Thank you for taking this on, it is a super handy tool!

I would just like to request possible future connection to Emby server to match up with Plex and Kodi. Thank you.

P.S. Sorry I am not sure how to make this a future request instead of an issue. :(

**Comment by Hellowlol** [comment] 2016-01-18 10:08
Dupe of https://github.com/Hellowlol/HTPC-Manager/issues/181

**Closed as completed by Hellowlol** 2016-01-18 10:08 UTC
